clean:
	-rm -Rf logs
	-rm -Rf crash-reports
	-rm betterfps.txt
	-rm minetweaker.log
	-rm OpenComputers*
	-rm Reika.*
	-rm TimeUsage.txt
	-rm usernamecache.json
	-rm settings.rtg
	-rm -Rf llibrary
	-rm -Rf backups
	-rm -Rf local
